### ISSUE TITLE
Defector Detector - Text

### ISSUE THREAD

**Issue by klinefk1** [joshfriend/bunnypedia#10]
Text on (0055) is slightly different than printed on the IMG. Could just be versioning of the card.

**Comment by klinefk1** [comment]
Also, in additional rules, `first` is spelled `rst` at the end of the first sentence.

**Comment by klinefk1** [comment]
Heavenly Halo message should end with a `.`

**Comment by joshfriend** [comment]
The cards i have are series ZZ which is newer than EE series cards.
