### ISSUE TITLE
Text in menu for Yellow Sinister is smaller than other title text

### ISSUE THREAD

**Issue by klinefk1** [joshfriend/bunnypedia#25]
Card 0114

**Comment by joshfriend** [comment]
screenshot? im not seeing this happen

**Comment by klinefk1** [comment]
Did not take a screenshot when I saw it the first time and cannot replicate. Probably good to close, but I'll reopen if I see it again.

**Comment by klinefk1** [comment]
Reopening- See screenshot:

![screenshot_20180114-213537](https://user-images.githubusercontent.com/9287821/34924777-7ed02a3a-f973-11e7-99a4-d6896e16e481.png)


`Feed All Your Bunnies 3/3` is much smaller than `Curry Spiced Poppadoms`, though both would fit fine at matching text size. 

This is very minor and maybe it's intentional based on the length of the string. Up to you whether you want to do anything with it or not.

**Comment by klinefk1** [comment]
Named Carrots Billy and Julie should be the same char length so I'm not sure why they would be sized differently. 
![screenshot_20180114-215728](https://user-images.githubusercontent.com/9287821/34925242-235d6a70-f976-11e7-99cd-cd36c58eaf34.png)

**Comment by klinefk1** [comment]
Last example - differently sized `Choose A Carrot`. 
![screenshot_20180114-220401](https://user-images.githubusercontent.com/9287821/34925375-f3709a0c-f976-11e7-8a7e-3b7a3e6b1ebd.png)

**Comment by joshfriend** [comment]
looks the `autoSizeTextType=uniform` in the `AppCompatTextView` used for the title isnt recomputing the size reliably when the ViewHolder is recycled.

**Comment by joshfriend** [comment]
I got rid of this layout style so it's no longer an issue
