### ISSUE TITLE
Weapon Level Formatting Discrepancy in Text

### ISSUE THREAD

**Issue by klinefk1** [joshfriend/bunnypedia#27]
In the text description of Blue and Yellow, weapons descriptions have texts that are similar to `May be placed on any bunny which must roll higher than 1 to survive.`  

This changes to`May be placed on any bunny which must roll higher than 01 to survive.` in the Red deck.  Probably should be consistent either way whether or not to prefix single digit roll results with 0.

**Comment by klinefk1** [comment]
See Mousetrap vs Ice Pick

**Comment by joshfriend** [comment]
I checked and it was actually printed that way. I changed it to be without the leading `0` anyways to be more consistent.
