### ISSUE TITLE
Omission of Conquest Yellow booster deck in Settings/Booster Deck causes off-by-one error

### ISSUE THREAD

**Issue by TheDavii** [joshfriend/bunnypedia#68]
Under Settings/Booster Decks, "Conquest Yellow" is omitted from the deck selection. The decks are listed Chocolate Booster, Conquest Blue Starter, Conquest Red Booster, .... With none of the booster deck checkboxes selected, the Pumpkin Spice Booster deck's cards are shown. With only the Pumpkin Spice Booster box selected, the Creature Feature deck's cards are shown in addition to the Pumpkin Spice booster deck's cards. This pattern continues back to the Conquest Red Booster. If Conquest Red is selected, the Conquest Yellow booster deck's cards are shown in addition to the Pumpkin Spice booster deck's cards.

**Comment by joshfriend** [comment]
Thanks, it's fixed and rolling out to beta now.
