### ISSUE TITLE
Bad (incorrect) data found in JSON files, after automated comparison to QCC, broken out by deck

### ISSUE THREAD

**Issue by TheDavii** [joshfriend/bunnypedia#86]
Bad (incorrect) data found in JSON files, after automated comparison to QCC, broken out by deck. These were verified by inspection of card scans:

Blue starter:

CardID = 70 Title = Geneva Convention
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

CardID = 74 Title = The Mad, Mad Donnelaith Bakery
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY

CardID = 75 Title = The Mad, Mad Donnelaith Bakery
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY

CardID = 81 Title = Rooney's Reusables
type:=
	Bunnypedia: SPECIAL
	QCC       : VERY_SPECIAL
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY

Yellow deck:

CardID = 121 Title = Choose A Carrot
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY

CardID = 122 Title = Choose A Carrot
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY

CardID = 123 Title = Choose 2 Carrots
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY

CardID = 124 Title = Choose 2 Carrots
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY

CardID = 131 Title = Sea Whiz Mount
Bunnypedia value for symbols = ['JUPITER'] *** This is incorrect ***
QCC value for symbols missing.

Red deck:

CardID = 202 Title = Show Me The Bunny
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

CardID = 208 Title = 1 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 209 Title = 2 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 210 Title = 3 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 211 Title = 3 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 212 Title = 3 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 213 Title = 5 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 214 Title = 5 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 215 Title = 10 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

Violet deck:

CardID = 245 Title = Rooney's Weapons Emporium - 5/Level
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 253 Title = Large Prune Danish
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

Orange deck:

CardID = 276 Title = Marilyn Bunroe - Single Specialty Bunny
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 277 Title = Bunnies Of Hazzard - Double Specialty Bunny
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 278 Title = Bunnylon 3 - Triple Specialty Bunny
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 279 Title = Those 70's Bunnies - Triple Specialty Bunny
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 298 Title = Lucky Clover – Heptdruple (Bunny Modifier)
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 308 Title = Incredibly Magic Fountain
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 309 Title = Incredibly Magic Fountain
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

Green:
CardID = 348 Title = Day Of The Dead
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY
dice:=
	Bunnypedia: ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'PINK']
	QCC       : ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'RED', 'PINK']

CardID = 357 Title = Wheels Chocolate
dice:=
	Bunnypedia: ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'RED', 'PINK']
	QCC       : ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'PINK']

ardID = 374 Title = Aries
zodiacType:=
	Bunnypedia: ARIES
	QCC       : FIRE

CardID = 375 Title = Taurus
zodiacType:=
	Bunnypedia: TAURUS
	QCC       : EARTH

CardID = 376 Title = Gemini
zodiacType:=
	Bunnypedia: GEMINI
	QCC       : AIR

CardID = 377 Title = Cancer
zodiacType:=
	Bunnypedia: CANCER
	QCC       : WATER

CardID = 378 Title = Leo
zodiacType:=
	Bunnypedia: LEO
	QCC       : FIRE

CardID = 379 Title = Virgo
zodiacType:=
	Bunnypedia: VIRGO
	QCC       : EARTH

CardID = 380 Title = Libra
zodiacType:=
	Bunnypedia: LIBRA
	QCC       : AIR

CardID = 381 Title = Scorpio
zodiacType:=
	Bunnypedia: SCORPIO
	QCC       : WATER

CardID = 382 Title = Sagittarius
zodiacType:=
	Bunnypedia: SAGITTARIUS
	QCC       : FIRE

CardID = 383 Title = Capricorn
zodiacType:=
	Bunnypedia: CAPRICORN
	QCC       : EARTH

CardID = 384 Title = Aquarius
zodiacType:=
	Bunnypedia: AQUARIUS
	QCC       : AIR

CardID = 385 Title = Pisces
zodiacType:=
	Bunnypedia: PISCES
	QCC       : WATER

Twilight White deck:

CardID = 421 Title = Free Pawn
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 430 Title = White Stuff
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

Perfectly Pink:

CardID = 504 Title = Feed All Your Bunnies 2/2
title:=
	Bunnypedia: Feed All Your Bunnies 2/2
	QCC       : Feed All Your Bunnies
cabbage:=
	Bunnypedia: 1
	QCC       : 2
water:=
	Bunnypedia: 1
	QCC       : 2

Whaky Khaki:

CardID = 590 Title = Terrible Misfortune – Pamplona
type:=
	Bunnypedia: RUN
	QCC       : PLAY_IMMEDIATELY

CardID = 600 Title = Ensign Rank O-1 (Bunny Modifier)
type:=
	Bunnypedia: RUN
	QCC       : RANK
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 601 Title = Lieutenant JG Rank O-2 (Bunny Modifier)
type:=
	Bunnypedia: RUN
	QCC       : RANK
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 602 Title = Lieutenant Rank O-3 (Bunny Modifier)
type:=
	Bunnypedia: RUN
	QCC       : RANK
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 603 Title = LT Commander Rank O-4 (Bunny Modifier)
type:=
	Bunnypedia: RUN
	QCC       : RANK
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 604 Title = Commander Rank O-5 (Bunny Modifier)
type:=
	Bunnypedia: RUN
	QCC       : RANK
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 605 Title = Captain Rank O-6 (Bunny Modifier)
type:=
	Bunnypedia: RUN
	QCC       : RANK

bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

Ominous Onyx deck:

CardID = 644 Title = Echo Valley 2-6809
dice:=
	Bunnypedia: ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'PINK']
	QCC       : ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'PINK', 'V10', 'O10', 'G10', 'Y10', 'B10']

CardID = 645 Title = The Fifth Element
dice:=
	Bunnypedia: ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'PINK']
	QCC       : ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'O10', 'G10', 'Y10', 'B10']

CardID = 680 Title = Dark Violets
type:=
	Bunnypedia: VERY_SPECIAL
	QCC       : PLAY_IMMEDIATELY

CardID = 682 Title = Very Terrible Misfortune – Irate ducks
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 683 Title = Extremely Terrible Misfortune – Instantaneous Proton Decay
type:=
	Bunnypedia: RUN
	QCC       : PLAY_IMMEDIATELY

CardID = 684 Title = 1 Dolla
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 685 Title = 1 Dolla
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 686 Title = 1 Dolla
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 687 Title = 2 Dolla
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

Chocolate deck:

CardID = 733 Title = Hitchbunny's Guide
dice:=
	Bunnypedia: ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'PINK']
	QCC       : ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'PINK', 'B10', 'G10', 'O10', 'V10', 'Y10']

Conquest Blue starter:

CardID = 0837 Title = Bizarre Baccarat
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

CardID = 0837 Title = Bizarre Baccarat
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

CardID = 0839 Title = Blue Plate Special
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

CardID = 0840 Title = Blue Plate Special
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

CardID = 0847 Title = Lemon Squeezie
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

*** 853 - 855 do not appear on the Bunnypedia app because Deck= PLAY_IMMEDIATELY ***

CardID = 0853 Title = Terrible Misfortune – Defibrillator
type:=
	Bunnypedia: RUN
	QCC       : PLAY_IMMEDIATELY
deck:=
	Bunnypedia: PLAY_IMMEDIATELY
	QCC       : CONQUEST_BLUE

CardID = 0854 Title = Terrible Misfortune – High Rise
type:=
	Bunnypedia: RUN
	QCC       : PLAY_IMMEDIATELY
deck:=
	Bunnypedia: PLAY_IMMEDIATELY
	QCC       : CONQUEST_BLUE

CardID = 0855 Title = Terrible Misfortune – Rolling Rock
type:=
	Bunnypedia: RUN
	QCC       : PLAY_IMMEDIATELY
deck:=
	Bunnypedia: PLAY_IMMEDIATELY
	QCC       : CONQUEST_BLUE

Conquest Red:

CardID = 0944 Title = Feed The Bunny 3/3
milk:=
	Bunnypedia: 1
	QCC       : 3

CardID = 0959 Title = Kentucky Avenue
dice:=
	Bunnypedia: ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED']
	QCC       : ['VIOLET', 'ORANGE', 'GREEN', 'YELLOW', 'BLUE', 'BLACK', 'RED', 'PINK'] *** Bunny Bits indicate Pink is used, but the card does not. ***

CardID = 0961 Title = Morden's Metals Exchange
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

Conquest Violet:
CardID = 0999 Title = Feed The Bunny 3/2
radish:=
	Bunnypedia: 4
	QCC       : 3
milk:=
	Bunnypedia: 1
	QCC       : 2

CardID = 1030 Title = Shiner Senator (Bunny Modifier)
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 1031 Title = Winer Senator (Bunny Modifier)
title:=
	Bunnypedia: Winer Senator (Bunny Modifier) *** KB web site incorrectly spells it "Winer." ***
	QCC       : Whiner Senator - Bunny Modifier *** card spells it "Whiner."
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 1039 Title = Copper
type:=
	Bunnypedia: DOLLA
	QCC       : METAL

CardID = 1040 Title = Silver
type:=
	Bunnypedia: DOLLA
	QCC       : METAL

Fantastic deck:

CardID = 1071 Title = Angry Nerds
type:=
	Bunnypedia: VERY_SPECIAL
	QCC       : RUN
bunnyRequirement:=
	Bunnypedia: NO
	QCC       : PLAY

CardID = 1072 Title = Omega Thirteen
type:=
	Bunnypedia: RUN
	QCC       : VERY_SPECIAL

CardID = 1090 Title = Zero Protection
type:=
	Bunnypedia: RUN
	QCC       : SPECIAL

Creature Feature deck:

CardID = 1176 Title = Funky Fungus Triple – (Bunny Modifier)
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

CardID = 1196 Title = Terrible Misfortune (Casting) – Hot Air Balloon
bunnyRequirement:=
	Bunnypedia: PLAY
	QCC       : NO

Pumpkin Spice deck:

CardID = 1259 Title = 2 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 1260 Title = 3 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 1261 Title = 5 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 1262 Title = 10 Dolla
type:=
	Bunnypedia: RUN
	QCC       : DOLLA

CardID = 1263 Title = Billon (Copper/Silver)
type:=
	Bunnypedia: RUN
	QCC       : METAL

CardID = 1264 Title = Electrum (Silver/Gold)
type:=
	Bunnypedia: RUN
	QCC       : METAL

CardID = 1265 Title = Tumbaga (Gold/Copper)
type:=
	Bunnypedia: RUN
	QCC       : METAL

**Comment by TheDavii** [comment]
In digging in a bit more, it looks like my program to find differences omitted differences where the keys were missing entirely from Bunnypedia (if a key existed in Bunnypedia, the same key was checked in the QCC, but if it didn't exist at all, it was never checked. It also doesn't check the rules and I found a set of minor differences with the rules, too. 

I'll post a more comprehensive list of differences in a few days.

**Comment by Mahobear8** [comment]
I found out a few days ago some of the cards are missing the MYSTERIOUS_PLACE_BALL symbol.  There are 18 cards that are said to have it.  There should be 27 according to the QCC.  If I find the time I'll make a list later today of the ones missing it.

**Comment by joshfriend** [comment]
This is super helpful, thank you. I will get to updating it eventually 😛

**Comment by TheDavii** [comment]
> 
> 
> I found out a few days ago some of the cards are missing the MYSTERIOUS_PLACE_BALL symbol. There are 18 cards that are said to have it. There should be 27 according to the QCC. If I find the time I'll make a list later today of the ones missing it.

Matthew, from listening to your vlog/podcast "Bunny Banter," it sounds like you have a spreadsheet (or maybe a database) that you use for statistics and attributes. Are there any attributes that your spreadsheet captured that aren't included in Bunnypedia or in the QCC (say, something one or both of us should add)?

**Comment by Mahobear8** [comment]
> > I found out a few days ago some of the cards are missing the MYSTERIOUS_PLACE_BALL symbol. There are 18 cards that are said to have it. There should be 27 according to the QCC. If I find the time I'll make a list later today of the ones missing it.
> 
> Matthew, from listening to your vlog/podcast "Bunny Banter," it sounds like you have a spreadsheet (or maybe a database) that you use for statistics and attributes. Are there any attributes that your spreadsheet captured that aren't included in Bunnypedia or in the QCC (say, something one or both of us should add)?

The database is created from the Bunnypedia JSON so nothing different

**Comment by TheDavii** [comment]
> 
> 
> This is super helpful, thank you. I will get to updating it eventually 😛

There were a lot more differences than I expected outside of the rules themselves (comparing the rules directly is challenging because of the many internal links, the different ordering we've chosen for adding Bunny Bits, and the like). You've already put a ton of work into this, so if it is easier, I can make replacement JSON files for you (and test against those for cleanup accuracy) and save you some work. 

I looked into making a pull request, but then I have to fork the repo and that seemed like even more work.

**Comment by TheDavii** [comment]
Josh, I programmatically modified and did some hand-editing of the attached JSON files.

I kept your titles, rules, rank, canonicalID, zodiacAnimal, weaponLevel and psi fields. I edited the few rules where I saw a repeated typo of "kinds" on the colored bunnies. All of the types, dice, symbols, radish, milk, water, cabbage, etc. (anything not listed above) came from the QCC. 

I compared the two outputs (Bunnypedia and QCC) iteratively as I made changes. As there were fewer differences as I "fixed" things, I noticed differences I hadn't seen before, so I cleaned up some of the card naming (e.g., "Blue Congenial" became "Blue Congenial Bunny" since "Bunny" is written on the card and the later bunnies like "Blue Breakdown Bunny" are written out fully). I also changed (or added) "(Bunny Modifier)" where cards were missing that descriptor in the name. I also corrected a few errors that were apparently copied from errors on the KillerBunnies.com web site. Oh, that includes the id as a string too. Should be easy to convert, but it looks like you must have added code to do that already since I saw one of the later boosters had id as a string. 

I included the Kinderbunnies 10-sided dice in the dice list where those are present on cards. "B10" is the Blue 10-sided die. "G10" is the Green 10-sided die, etc.  I hope that doesn't cause issues for your code.

I even found two minor errors in the QCC that I fixed as a result of the comparison. So 5 hours well spent!

**Comment by Mahobear8** [comment]
> Josh, I programmatically modified and did some hand-editing of the attached JSON files.
> [modified_bunnypedia_json.zip](https://github.com/joshfriend/bunnypedia/files/3464393/modified_bunnypedia_json.zip)
> 
> I kept your titles, rules, rank, canonicalID, zodiacAnimal, weaponLevel and psi fields. I edited the few rules where I saw a repeated typo of "kinds" on the colored bunnies. All of the types, dice, symbols, radish, milk, water, cabbage, etc. (anything not listed above) came from the QCC.
> 
> I compared the two outputs (Bunnypedia and QCC) iteratively as I made changes. As there were fewer differences as I "fixed" things, I noticed differences I hadn't seen before, so I cleaned up some of the card naming (e.g., "Blue Congenial" became "Blue Congenial Bunny" since "Bunny" is written on the card and the later bunnies like "Blue Breakdown Bunny" are written out fully). I also changed (or added) "(Bunny Modifier)" where cards were missing that descriptor in the name. I also corrected a few errors that were apparently copied from errors on the KillerBunnies.com web site. Oh, that includes the id as a string too. Should be easy to convert, but it looks like you must have added code to do that already since I saw one of the later boosters had id as a string.
> 
> I included the Kinderbunnies 10-sided dice in the dice list where those are present on cards. "B10" is the Blue 10-sided die. "G10" is the Green 10-sided die, etc. I hope that doesn't cause issues for your code.
> 
> I even found two minor errors in the QCC that I fixed as a result of the comparison. So 5 hours well spent!

This was very helpful for correcting my database that I reference for Bunny Banter.  Thanks Glenn!

**Comment by TheDavii** [comment]
The comparison also allowed me to send a list of 9 typos on the Killerbunnies.com web site (the source of some of the naming errors) to Jonathan Young, who corrected them by Sunday evening. 

Additionally, I realized that I used the zodiacType from the QCC rather than Bunnypedia. In Bunnypedia, the zodiacType was the same as the name (Virgo = Virgo), while in the QCC, the zodiacType was the Air, Earth, Fire, and Water, necessary for a Mysterious Place theft at the end of the game. Since there are only 12, it should be fairly quick to change them back manually. Or, I can generate a new Green JSON. Thoughts?

**Comment by joshfriend** [comment]
> Or, I can generate a new Green JSON. Thoughts?

I can make those small changes manually.

**Comment by TheDavii** [comment]
Found an error of mine in the export of The Fifth Element in Onyx (missing dice Pink and V10), so I fixed the cause of the error in Onyx and re-created Green to address the issue of zodiacType (not being the same as the name) while I was at it.  All other files in the archive are same as the first modification. 

[modified_bunnypedia_json_2019-08-12.zip](https://github.com/joshfriend/bunnypedia/files/3495139/modified_bunnypedia_json_2019-08-12.zip)

**Comment by joshfriend** [comment]
> I found out a few days ago some of the cards are missing the MYSTERIOUS_PLACE_BALL symbol. There are 18 cards that are said to have it. There should be 27 according to the QCC.

I found a few where the `symbols` field was missing after checking all of the card images. I still only count 24 though @Mahobear8

> "Blue Congenial" became "Blue Congenial Bunny" since "Bunny" is written on the card and the later bunnies like "Blue Breakdown Bunny" are written out fully). I also changed (or added) "(Bunny Modifier)" where cards were missing that descriptor in the name.

This is a good change. This fixes an issue where searching for "bunny" does not show most of the actual bunny cards!

> I included the Kinderbunnies 10-sided dice in the dice list where those are present on cards. "B10" is the Blue 10-sided die. "G10" is the Green 10-sided die, etc. I hope that doesn't cause issues for your code.

I made a separate issue to track adding D10 dice to the database (#89). 

> I used the zodiacType from the QCC rather than Bunnypedia. In Bunnypedia, the zodiacType was the same as the name

That's a poor choice on my part in the name I chose for that field. I've renamed it to `zodiacSign`. The zodiac element (fire, water, etc) is not in the json data and is computed from the sign in the app.

**Comment by Mahobear8** [comment]
Should be current full list of Mysterious Place Ball cards:
0051 0082 0154 0250 0319 0362 0394 0415 0449 0478 0525 0530 0563 0573 0628 0678 0723 0852 0955 1069 1075 1090 1116 1123 1130 1183
Kinder:
030
With release of London:
1287

Thus, bunnypedia should currently have 26 since it doesn't yet have London or Kinder.
Correct me if any of the IDs listed don't have it, I got it from QCC so will need to be corrected if wrong

**Comment by TheDavii** [comment]
> Should be current full list of Mysterious Place Ball cards:
> 0051 0082 0154 0250 0319 0362 0394 0415 0449 0478 0525 0530 0563 0573 0628 0678 0723 0852 0955 1069 1075 1090 1116 1123 1130 1183
> Kinder:
> 030
> With release of London:
> 1287

1287 is Mushy Peas. Unless you've heard a clarification from JB, I believe that card has a pea-green ball with a red stripe, which does not qualify it to be a Yellow Ball card. Do you mean 1274 (Gryffin Bunnies), which has a Yellow Ball in the form of a Quidditch Golden Snitch? That's what we're listing in the next version of the QCC. 

> 
> Thus, bunnypedia should currently have 26 since it doesn't yet have London or Kinder.
> Correct me if any of the IDs listed don't have it, I got it from QCC so will need to be corrected if wrong

I confirm 26 without London or Kinder.

**Comment by Mahobear8** [comment]
Ah, I did miss 1274, good catch.  I have not officially heard a clarification from JB for 1287, but in reference to Kris declaring it a green ball with red stripe in the Bunny Banter episode, Jeff replied "Green Ball.....?  Hilarious."  I interpreted that as this is intended to mechanically be the yellow-ball with red stripe symbol, but the coloring is off for thematic reasons, but if you'd like to further clarify with him, it may be a good idea.  Who knows, maybe Kris will be correct and Green Ball with Red Stripe will be a new mechanic (I personally doubt it)

**Comment by joshfriend** [comment]
Viva Las Vegas and Ultimate Chaos are particularly hard to spot, no wonder I missed those! I count 26 not including Kinder as well now.

**Comment by Mahobear8** [comment]
A bit off topic, but that brings up an interesting question.  What exactly does the Yellow Ball with Red Stripe do on Ultimate Chaos?  Since the mechanic always has to control the card within the rules of the card, exactly what control is there?  I can't think of any variance that could occur
@TheDavii

**Comment by joshfriend** [comment]
Since it's "play immediately", applies to "all players", and doesn't say "may be used" I don't think there's anything to control in that case.

**Comment by TheDavii** [comment]
> Since it's "play immediately", applies to "all players", and doesn't say "may be used" I don't think there's anything to control in that case.

A lot off-topic, but the rule for Control of the Yellow Ball says (in part), "The opponent must play the card first, then the player may redirect it to any other player, bunny _or the Discard Pile_." [emphasis added]

Therefore, I will argue that the Yellow Ball mechanic does apply. Practically speaking, with this Play Immediately, the player with the Yellow Ball with the Red Stripe can prevent the "ultimate" chaos by discarding it. Perhaps players can negotiate (bribe) the Yellow Ball player to force its discard.

**Comment by Mahobear8** [comment]
However, we know with Terrible Misfortunes that since discarding the card is not an option within the rules, the Yellow Ball cannot force it to be discarded.  I'd have to find it, but I recall Jeff clarifying mechanically it can only control within the rules of the card.  Therefore, since it's not normally an option to discard Ultimate Chaos, I wouldn't think the Yellow Ball would grant that power.  I agree with Josh here.  Mechanically speaking, the safest assumption is that it doesn't do anything here, but certainly Jeff could clarify otherwise for this to be an exception
